dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install poetry==1.0.2
  - poetry install 

script:
  - pytest
  - pip install codecov
  - codecov
  - pip install codacy-coverage
  - python-codacy-coverage -r coverage.xml

jobs:
  include:
    - stage: mypy
      script: 
        - echo "Run mypu"
        - pip install mypy
        - mypy conflow
      # Keep in mind to overwrite these here
      python: 3.8
